In [1]:
library(nlme) 

In [2]:
bloodsugar <- read.csv("bloodsugar.csv")

##Creamos las matrices:##

In [3]:
Y <- data.matrix(bloodsugar[,1:5])

In [4]:
X1 <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
X2 <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
X1
X2

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [5]:
X <- rbind(cbind(X1,X2),cbind(X2,X1),cbind(X1,X2),cbind(X2,X1))
Z <- rbind(rep(1,5),c(0,1.5,3,4.5,6))

In [6]:
X
Y
Z

X1 X2
 [1,] 1  0 
 [2,] 1  0 
 [3,] 1  0 
 [4,] 1  0 
 [5,] 1  0 
 [6,] 1  0 
 [7,] 1  0 
 [8,] 1  0 
 [9,] 1  0 
[10,] 1  0 
[11,] 1  0 
[12,] 1  0 
[13,] 1  0 
[14,] 1  0 
[15,] 1  0 
[16,] 1  0 
[17,] 1  0 
[18,] 1  0 
[19,] 1  0 
[20,] 1  0 
[21,] 1  0 
[22,] 1  0 
[23,] 0  1 
[24,] 0  1 
[25,] 0  1 
[26,] 0  1 
[27,] 0  1 
[28,] 0  1 
[29,] 0  1 
[30,] 0  1 
[31,] ⋮  ⋮ 
[32,] 1  0 
[33,] 1  0 
[34,] 1  0 
[35,] 1  0 
[36,] 1  0 
[37,] 1  0 
[38,] 1  0 
[39,] 1  0 
[40,] 0  1 
[41,] 0  1 
[42,] 0  1 
[43,] 0  1 
[44,] 0  1 
[45,] 0  1 
[46,] 0  1 
[47,] 0  1 
[48,] 0  1 
[49,] 0  1 
[50,] 0  1 
[51,] 0  1 
[52,] 0  1 
[53,] 0  1 
[54,] 0  1 
[55,] 0  1 
[56,] 0  1 
[57,] 0  1 
[58,] 0  1 
[59,] 0  1 
[60,] 0  1 
[61,] 0  1

L1  L2 L3 L4  L5 
 [1,]  77 52 35  56  64
 [2,]  90 47 52  68  90
 [3,]  85 52 35  39  60
 [4,]  94 60 60  77  94
 [5,]  77 56 43  56  64
 [6,]  85 52 60  81  94
 [7,] 103 26 68  30  30
 [8,] 107 60 68  90  94
 [9,]  77 43 64  39  64
[10,]  90 30 30  47  60
[11,]  99 39 39  73  90
[12,] 103 60 60  90  99
[13,]  81 56 22  35  39
[14,] 107 47 47  47  73
[15,]  77 26 56  64  64
[16,] 116 52 26  68 120
[17,]  90 73 52  60  64
[18,]  94 60 60  77  90
[19,]  90 60 18  35  64
[20,]  94 56 47  81  99
[21,] 103 47 22  60  99
[22,]  90 47 30  43  68
[23,]  85 56 56  77  94
[24,] 111 73 85 103 111
[25,]  99 47 52  47  81
[26,]  99 26 64  52  90
[27,]  90 43 18  30  39
[28,] 111 56 43  90 111
[29,]  90 35 22  26  22
[30,]  94  8 30  26  43
[31,] ⋮   ⋮  ⋮  ⋮   ⋮  
[32,]  90 12 43  85  99
[33,]  92 52 73  99 101
[34,]  85 35 39  85  77
[35,]  85 47 56  77  81
[36,]  90 43 35  64  81
[37,]  85 52 52  77  99
[38,] 103 56 47  64  56
[39,] 103 35 39  68  99
[40,]  90 35 18  64  94
[41,] 107 47 43  85 101
[42,]  90 52 35  35  39
[43,]  90 43 30  47  77
[44,]  77 56 64  81  99
[45,] 111 60 68 107 111
[46,]  81 22 12  22  77
[47,]  81 12  2  30  77
[48,]  68 12  8   8  39
[49,]  85 26 12  18  39
[50,]  85 30 22  52  94
[51,]  90 30 26  52  90
[52,]  85 39 22  56  90
[53,] 105 68 64  81  81
[54,]  85 47 33  77 107
[55,]  85 39 39  43  60
[56,]  85 35 26  43  73
[57,]  90 43 35  81  90
[58,]  94 39 35  52  85
[59,]  94 26 30  39  81
[60,]  90 22 26  73  99
[61,] 103 47 35  64  94

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1.0  1    1.0  1   
[2,] 0    1.5  3    4.5  6

##Construimos el Estimador de B##

In [7]:
XX <- crossprod(X)
ZZ <- crossprod(t(Z))
XYZ <- crossprod(X, Y%*%t(Z))
B <- solve(XX, XYZ%*%solve(ZZ))

In [8]:
XX
ZZ
XYZ

X1 X2
X1 44  0
X2  0 44

[,1] [,2]
[1,]  5   15.0
[2,] 15   67.5

[,1]  [,2]   
X1 14432 43200.0
X2 13554 40228.5

In [9]:
B

[,1]     [,2]      
X1 65.89091 -0.0969697
X2 62.92273 -0.4378788

##Construimos el Estimador para Sigma##

In [10]:
res <- Y-X%*%B%*%Z
n <- nrow(Y)
Sigma <- crossprod(res)/n
Sigma

L1          L2        L3        L4         L5       
L1  840.467614 -499.0819 -565.8846  -5.108796  582.2078
L2 -499.081875  634.9414  607.0630 227.915943 -290.5900
L3 -565.884566  607.0630  859.1196 324.867283 -319.9732
L4   -5.108796  227.9159  324.8673 476.548866  290.1517
L5  582.207831 -290.5900 -319.9732 290.151705  827.7413

##Finalmente Calculamos la Varianza estimada del estimador de B##

In [11]:
kronecker(solve(XX), solve(ZZ, Z%*%Sigma%*%t(Z))%*%solve(ZZ))

[,1]       [,2]       [,3]       [,4]      
[1,]  2.8580510 -0.2757285  0.0000000  0.0000000
[2,] -0.2757285  0.3048390  0.0000000  0.0000000
[3,]  0.0000000  0.0000000  2.8580510 -0.2757285
[4,]  0.0000000  0.0000000 -0.2757285  0.3048390